version: '3'
services:
  frontend:
    image: jqpp11/website-frontend:latest
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE_URL=http://localhost/api
    depends_on:
      - server

  server:
    image: jqpp11/website-server:latest
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=website_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - server

volumes:
  mysql_data:

